# Generated by Django 5.2.1 on 2025-05-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='logout_type',
            field=models.CharField(blank=True, choices=[('manual', 'Logout Manual'), ('expired', 'Sesión Expirada'), ('forced', 'Logout Forzado'), ('password_change', 'Cambio de Contraseña')], max_length=20, null=True),
        ),
    ]
